module Aeos
  module Blake512
    VERSION: String

    class BuildMismatch < LoadError
    end

    def self.digest: (String bytes) -> String
    def self.hexdigest: (String bytes) -> String
    def self.build_info: () -> Hash[String, untyped]
  end
end
